# Generated by Django 4.0.3 on 2022-03-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
                ('filename', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Excel Document',
                'verbose_name_plural': 'Excel Documents',
            },
        ),
    ]
